use crate::assembly::assembly_result::AssemblyResult;
use crate::assembly::node_datum::NodeDatum;
use crate::io::json::{ParaphaseOutput, ReadAlignmentId, ReadFingerprintMap};
use crate::toolkit::util::{DError, HashMap};

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

use vstr::{VStr, VString};

use petgraph::stable_graph::StableGraph as PetGraph;

/**
 * `Graph` class, port of the `Paraphase` equivalent class.
 * It is generated from a set of alignment ids (name + optional alignment number)
 * and associated fingerprints, as generated by alignments and variant site selection.
 *
 * The original implementation uses python structures to store nodes, edges,
 * and provide access to each.
 * We currently use a mix of petgraph and dictionary structures to support graph properties.
 *
 * `ReadAlignmentId` replaces the string names of reads.
 * This is because unlike Paraphase, we want to phase VNTRs, and it's therefore possible to have multiple alignments per read.
 * Most are straight ports, but typed.
 * We describe the exceptions here.
 * 1. For paralog/homolog phasing, there is simply no alignment id associated.
 *    This replaces `{read_name: read_hap}` for reads.
 * 2. The Graph Structure.
 *   In paraphase, it is made up of:
 *     List of edges
 *     List of nodes
 *     next-per-node and previous-per-node
 *     `edge_info`: map from edge to counts of supporting reads.
 *     `edge_per_position`: map from positions to edges
 *
 *  We use `petgraph` to store most of the data:
 *     We use a directed graph with `NodeType(String, position as u32)` as node type and `Vec<u32>` as edge type.
 *     These `u32`s identify which readalignments support the specific edge.
 *
 *  In addition to the graph structure, we have some helper objects.
 * `read_aln_id_map`: `HashMap` from `ReadAlignmentId` to a numeric id associated with it so that it's easy to pass around an identifier.
 * `node_id_map`: `HashMap` to look up a node's numeric id from the node value.
 *
 * `pos_edge_map` is a straight port of `edge_per_position`.
 * We do not store `edge_info` because its information is stored in `pos_edge_map`.
 *
 * When adding a node, one needs to update `id_node_by_map` to both get the id and see if it was newly inserted.
 *
 */

#[derive(Debug, Clone)]
pub struct GraphError {
    pub msg: String,
}

impl GraphError {
    #[must_use]
    /// Create a graph-construction/assembly error with message context.
    pub fn new(x: impl Into<String>) -> Self {
        Self { msg: x.into() }
    }
}

impl std::error::Error for GraphError {}

impl std::fmt::Display for GraphError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "GraphError{{msg: {}}}", self.msg)
    }
}

/// Class describing nature of the graph at a given position.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SegmentationClass {
    Unassigned,
    Two, // Unambiguous: only one out edge
    Ten, // Ambiguous: multiple out edges
}

impl SegmentationClass {
    #[must_use]
    /// Whether this position has been classified into a concrete segmentation state.
    pub fn is_assigned(&self) -> bool {
        matches!(self, Self::Two | Self::Ten)
    }
}

pub type NodeType = NodeDatum;
pub type EdgeType = Vec<u32>; // Vector of read ids
pub type IxType = u32;
pub type VGraph = PetGraph<NodeType, EdgeType, petgraph::Directed, IxType>;
/// best match score + vector of matches sharing that score.
pub type MatchingHapSet<'a> = (i32, Vec<VStr<'a>>);

/// Settings for `Graph` haplotype assembler.
/// Most use cases will use default.
///
/// `min_match_count`: Minimum number of fingerprint positions for matching reads against candidate haplotypes. Raising this increases specificity but reduces sensitivity.
/// `min_hap_support`: Minimum number of reads supporting a haplotype for final filtering.
/// `pivot_index`: Used for partitioning the graph based on a pivot position.
///
/// Defaults to `(4, 1, 0)`.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct Settings {
    pub min_match_count: i32, /* Minimum number of fingerprint positions for matching reads against candidate haplotypes. Raising this increases specificity but reduces sensitivity. */
    pub min_hap_support: i32, /* Minimum number of reads supporting a haplotype for final filtering. */
    pub pivot_index: i64,     // Used for partitioning the graph based on a pivot position.
}

impl std::default::Default for Settings {
    fn default() -> Self {
        Self {
            min_hap_support: 4,
            min_match_count: 1,
            pivot_index: -1,
        }
    }
}

impl Settings {
    /// Construct settings from a pivot index, otherwise using defaults of 1 match for partial haplotypes and minimum 4 read support for inclusion.
    #[must_use]
    pub fn from_pivot(pivot_index: Option<i64>) -> Self {
        let pivot_index = pivot_index.unwrap_or(-1);
        log::debug!("Building graph settings from pivot_index={pivot_index}");
        Self {
            pivot_index,
            ..Default::default()
        }
    }
}

pub type NodeMapType = BTreeMap<NodeDatum, u32>;

/// For ease - tuple. `(from_id, to_id, count)`
pub type WeightedEdge = (u32, u32, u32);

/// `Graph` is the core data structure for haplotype assembly.
/// Using a set of extracted fingerprints, it segments the graph, assembles local regions, and then chains them
/// into a set of assembled haplotypes.
/// Typically created from `ReadFingerprintMap`, a map from `ReadAlignmentId` to `VString`.
/// The `Option<i32>` member for `ReadAlignmentId` allows us to have multiple fingerprints per read.
#[derive(Debug, Default)]
pub struct Graph {
    pub settings: Settings,
    pub nvar: usize,
    pub reads: ReadFingerprintMap,
    pub reads_original: ReadFingerprintMap,
    pub graph: VGraph,
    pub(crate) read_aln_id_map: BTreeMap<ReadAlignmentId, u32>,
    pub node_id_map: NodeMapType, // Map from NodeDatum (hap, position) to index
    pub pos_edge_map: BTreeMap<usize, Vec<WeightedEdge>>, /* Vector from position to all the edges at that position. */
    pub edge_info: Vec<Vec<u32>>,                         // Vector of vectors of counts.
    pub dnhap: BTreeMap<u32, SegmentationClass>, /* Copy of dnhap from paraphase, except we use Option<i32> instead of i32 with -1 as a special case. */
    pub(crate) node_positions: HashMap<u32, (u32, u32)>,
    pub(crate) total_node_count: usize, /* Total number of nodes. Needed to maintain node numbering while handling deletions. */
}

impl std::ops::Deref for Graph {
    type Target = VGraph;
    fn deref(&self) -> &Self::Target {
        &self.graph
    }
}

impl std::ops::DerefMut for Graph {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.graph
    }
}

impl std::convert::TryFrom<&ParaphaseOutput> for Graph {
    type Error = GraphError;
    fn try_from(x: &ParaphaseOutput) -> Result<Self, Self::Error> {
        Self::try_from(x.clone())
    }
}

impl std::convert::TryFrom<ParaphaseOutput> for Graph {
    type Error = GraphError;
    fn try_from(x: ParaphaseOutput) -> Result<Self, Self::Error> {
        let pivot_index = x.pivot_index(None);
        Self::try_new(x.read_to_hap, Some(Settings::from_pivot(Some(pivot_index))))
    }
}

/// Stores a view to a read name + align id + an associated path.
/// This lets us return references to the relevant alignment without copying data.
#[derive(Clone, Copy, Hash, Eq, PartialEq)]
pub struct ReadHapPair<'a> {
    pub name: &'a str,
    pub path: &'a VString,
}

impl<'a> std::fmt::Display for ReadHapPair<'a> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}-{}", self.name, self.path)
    }
}

impl<'a> std::fmt::Debug for ReadHapPair<'a> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{self}")
    }
}

/// Maps from hap ids to read alignments (unique and ambiguous), as well as a map from read alignments
/// to potential hap ids.
/// Compared to the python implementation, we use numeric u32 ids for the provided fingerprints instead of a reference to the path itself for lifetime management ease.
#[derive(Clone)]
pub struct ReadHapSupport<'a> {
    pub support_reads: HashMap<u32, Vec<ReadHapPair<'a>>>, /* hap ids and their unique matches. Read alignments here have a unique haplotype match. */
    pub support_reads_nonunique: HashMap<u32, Vec<ReadHapPair<'a>>>, /* hap ids and their non-unique matches. Read alignments here have more than one candidate haplotype/fingerprint. */
    pub supporting_haps_per_read: HashMap<ReadHapPair<'a>, Vec<u32>>,
}

impl<'a> std::fmt::Debug for ReadHapSupport<'a> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(
            f,
            "Support: {:?}\nAmbiguous Support: {:?}\n: HapsPerRead: {:?}",
            self.support_reads, self.support_reads_nonunique, self.supporting_haps_per_read
        )
    }
}

pub type DBeforeNext<'a> = BTreeMap<VStr<'a>, BTreeSet<VStr<'a>>>;

/// Definition for results after merging positions.
pub type MergePosResult<'a> = (
    BTreeMap<VString, Vec<&'a ReadAlignmentId>>,
    DBeforeNext<'a>,
    DBeforeNext<'a>,
);

/// When we merge subregions, we receive a 4-tuple.
/// bool: assembly success
/// `pos1_haps`: `Vec<VString>` - assembled haps.
/// where `dnext` and `dbefore` has pairs of connected fingerprint substrings.
/// `dnext`, `dbefore`: `BTreeMap<VString, BTreeSet<VString>>`.
pub type SubregionResult = (
    bool,
    Vec<VString>,
    BTreeMap<VString, BTreeSet<VString>>,
    BTreeMap<VString, BTreeSet<VString>>,
);

impl Graph {
    /// Construct a `Graph` from a Map of (read: hap) and optional settings.
    ///
    /// For a fallible constructor, use `Graph::try_new`.
    /// If settings is `None`, uses `Settings::default()`
    ///
    #[must_use]
    pub fn new(reads: ReadFingerprintMap, settings: Option<Settings>) -> Self {
        Self::try_new(reads, settings).unwrap_or_else(|e| {
            log::warn!("Graph::new failed to construct graph: {e:?}. Returning default graph.");
            Self::default()
        })
    }

    /// Construct a `Graph` from a Map of (read: hap) and optional settings.
    ///
    /// # Errors
    /// Returns an error when input read fingerprints are inconsistent or cannot
    /// initialize internal graph state.
    /// If settings is `None`, uses `Settings::default()`
    /// # Errors
    /// 1. `GraphError` - inconsistent number of variant sites, too few sites.
    pub fn try_new(
        reads: ReadFingerprintMap,
        settings: Option<Settings>,
    ) -> Result<Self, GraphError> {
        log::trace!("Building graph from read fingerprints: {reads:?}");
        let settings = settings.unwrap_or_default();
        let sizes = reads.values().map(|x| x.len()).collect::<BTreeSet<_>>();
        match sizes.len() {
            0 => return Err(GraphError::new(String::from("No input reads to assemble."))),
            1 => {}
            _ => {
                return Err(GraphError::new(format!("Found multiple sizes: {sizes:?}")));
            }
        }
        let nvar = sizes.iter().copied().next().unwrap_or(0);
        if nvar < 1 {
            return Err(GraphError::new(format!("Too few sites: {nvar}")));
        }
        let read_aln_id_map = reads
            .keys()
            .enumerate()
            .map(|(idx, name)| (name.clone(), idx as u32))
            .collect::<BTreeMap<_, _>>();
        let reads_original = reads.clone();
        Ok(Self {
            settings,
            nvar,
            reads,
            reads_original,
            read_aln_id_map,
            graph: VGraph::with_capacity(nvar, nvar * 2),
            ..Default::default()
        })
    }

    /// Run full construction: initialize graph and run assembly.
    pub fn construct(&mut self) -> Result<AssemblyResult, DError> {
        self.init()?;
        self.run_asm()
    }
} // Graph

#[cfg(test)]
mod tests {
    use crate::assembly::assembly_result::AssembledPaths;
    use crate::assembly::node_datum::NodeDatum;
    use crate::assembly::variant_graph::Graph;
    use itertools::Itertools;
    use petgraph::stable_graph::NodeIndex;
    use petgraph::visit::{EdgeRef, IntoEdgeReferences};
    use std::collections::BTreeMap;

    // Corresponds to tests/test_haplotype_assembler.py:test_initialize_graph
    mod init_graph {
        use super::*;
        use crate::io::json::{ReadAlignmentId, ReadFingerprintMap};
        use crate::toolkit::util::DResult;
        #[test]
        fn test_graph_constructor_ok() -> DResult {
            use crate::assembly::variant_graph::*;
            use itertools::Itertools;
            let mut read_inputs = [
                ("r1", "11x"),
                ("r2", "11x"),
                ("r3", "22x"),
                ("r4", "22x"),
                ("r5", "x12"),
                ("r6", "x22"),
                ("r7", "x2x"),
                ("r8", "x22"),
                ("r9", "x11"),
                ("r10", "x11"),
                ("r11", "x22"),
                ("r12", "x22"),
                ("r13", "x22"),
                ("r14", "x22"),
                ("r15", "x11"),
                ("r16", "x11"),
                ("r17", "x11"),
                ("r18", "x11"),
            ]
            .into_iter()
            .map(|(x, y)| (ReadAlignmentId::from_name(x), vstr::VString::from(y)))
            .collect::<ReadFingerprintMap>();
            let mut graph = Graph::try_new(read_inputs.clone(), None)?;
            graph.init()?;
            let expected_nodes = [(1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)];
            let expected_nodes = expected_nodes
                .into_iter()
                .map(|(value, position)| {
                    let value = value as u8 + b'0';
                    NodeDatum::from((value, position as usize))
                })
                .sorted()
                .collect::<Vec<_>>();
            let nodes = graph.node_iter().cloned().sorted().collect::<Vec<_>>();
            assert_eq!(nodes, expected_nodes);
            let edges = graph
                .graph
                .edge_references()
                .map(|edge| {
                    graph
                        .paraphase_format_edge(edge.id(), None)
                        .expect("Edge missing")
                })
                .sorted()
                .collect::<Vec<(String, String)>>();

            let expected_edges = [
                ("1-0", "1-1"),
                ("2-0", "2-1"),
                ("2-1", "2-2"),
                ("1-1", "1-2"),
            ]
            .into_iter()
            .map(|(x, y)| (String::from(x), String::from(y)))
            .sorted()
            .collect::<Vec<(String, String)>>();
            assert_eq!(edges, expected_edges);

            assert!(!graph.reads.contains_key(&ReadAlignmentId::from_name("r5")));

            // Now remove node and test read allowance.
            // r5 should be present now.
            assert!(read_inputs
                .remove(&ReadAlignmentId::from_name("r18"))
                .is_some());

            let mut graph = Graph::try_new(read_inputs.clone(), None)?;
            graph.init()?;

            let nodes = graph.node_iter().cloned().sorted().collect::<Vec<_>>();
            assert_eq!(nodes, expected_nodes);

            let edges = graph
                .graph
                .edge_references()
                .map(|edge| {
                    graph
                        .paraphase_format_edge(edge.id(), None)
                        .expect("Nodes missing from graph.")
                })
                .sorted()
                .collect::<Vec<(String, String)>>();
            let expected_edges = [
                ("1-0", "1-1"),
                ("2-0", "2-1"),
                ("1-1", "2-2"),
                ("2-1", "2-2"),
                ("1-1", "1-2"),
            ]
            .into_iter()
            .map(|(x, y)| (String::from(x), String::from(y)))
            .sorted()
            .collect::<Vec<(String, String)>>();
            assert_eq!(edges, expected_edges);
            assert!(graph.reads.contains_key(&ReadAlignmentId::from_name("r5")));
            assert!(!graph.pos_edge_map.is_empty());
            {
                let map = &graph.pos_edge_map;
                log::debug!("Edge/link map state: {map:?}");
                let format_edge = |edge: &WeightedEdge| -> (String, String, u32) {
                    let source = NodeIndex::new(edge.0 as usize);
                    let target = NodeIndex::new(edge.1 as usize);
                    let res = graph
                        .paraphase_format_edge(
                            graph
                                .find_edge(source, target)
                                .expect("Missing edge from graph"),
                            None,
                        )
                        .expect("Failed to format edge pair");
                    (res.0, res.1, edge.2)
                };
                assert_eq!(map.len(), 2);
                assert_eq!(map[&0].len(), 2);
                assert_eq!(map[&1].len(), 3);
                assert_eq!(
                    &map[&0].iter().map(format_edge).collect::<Vec<_>>()[..],
                    &[
                        (String::from("1-0"), String::from("1-1"), 2),
                        (String::from("2-0"), String::from("2-1"), 2)
                    ]
                );
            }
            Ok(())
        }
        #[test]
        fn summarize_edges_ok() -> DResult {
            use crate::assembly::variant_graph::SegmentationClass;
            use crate::assembly::variant_graph::SegmentationClass::*;
            use std::collections::BTreeMap;
            let read_inputs = [("r1", "11"), ("r2", "22")]
                .into_iter()
                .map(|(x, y)| (ReadAlignmentId::from_name(x), vstr::VString::from(y)))
                .collect::<ReadFingerprintMap>();
            let mut graph = crate::assembly::variant_graph::Graph::try_new(read_inputs, None)?;
            for node in [
                (b'1', 0), // 0
                (b'2', 0), // 1
                (b'1', 1), // 2
                (b'2', 1), // 3
                (b'1', 2), // 4
                (b'2', 2), // 5
                (b'1', 3), // 6
                (b'2', 3), // 7
                (b'1', 4), // 8
                (b'2', 4), // 9
            ]
            .into_iter()
            .map(|(chr, pos)| NodeDatum::from((chr, pos as usize)))
            {
                let (_id, was_new) = graph.fully_add_node(node);
                assert!(was_new);
            }
            assert_eq!(graph.total_node_count, 10);
            assert_eq!(graph.node_id_map.len(), 10);
            let mut edges: BTreeMap<usize, Vec<(u32, u32, u32)>> = BTreeMap::new();
            edges.insert(0, vec![(0, 2, 2), (1, 3, 3)]);
            edges.insert(1, vec![(2, 5, 2), (3, 5, 6), (2, 4, 5)]);
            edges.insert(2, vec![(4, 7, 2), (5, 7, 6), (4, 6, 5)]);
            edges.insert(3, vec![(6, 9, 2), (7, 9, 6), (6, 8, 5)]);
            for edge_set in edges.values() {
                for (from, to, _count) in edge_set {
                    //for (from, to, _count) in edges.iter().flatten().copied() {
                    graph.add_edge((*from).into(), (*to).into(), vec![]);
                }
            }
            graph.pos_edge_map = edges;
            graph.summarize_edges()?;
            let expected_dnhap = [(0, Two), (1, Ten), (2, Ten), (3, Ten)]
                .into_iter()
                .collect::<BTreeMap<u32, SegmentationClass>>();
            log::debug!("Found {:?} dnhap, expected {expected_dnhap:?}", graph.dnhap);
            assert_eq!(expected_dnhap, graph.dnhap);
            Ok(())
        }
    } // init_graph

    mod other_tests {
        use super::*;
        use crate::assembly::variant_graph;
        use crate::io::json::{ReadAlignmentId, ReadFingerprintMap};
        use crate::toolkit::range::Range;
        use crate::toolkit::util::{DError, DResult};

        #[test]
        fn test_get_next_pos() -> Result<(), std::boxed::Box<dyn std::error::Error>> {
            use vstr::VString;
            // Set up graph.
            let mut reads = ReadFingerprintMap::new();
            reads.insert(ReadAlignmentId::from_name("r1"), VString::from("11"));
            reads.insert(ReadAlignmentId::from_name("r2"), VString::from("22"));
            let mut graph = Graph::try_new(reads.clone(), None)?;
            let mut add_node = |x: VString, y: u32| {
                let _added = graph.fully_add_node(NodeDatum::new(x, y));
            };
            add_node(VString::from("121"), 0);
            add_node(VString::from("111"), 0);
            add_node(VString::from("222"), 3);
            add_node(VString::from("111"), 3);

            // Get next for 1
            let res = graph.get_next_pos(1).unwrap();
            assert_eq!(res, 3u32);
            let prev_haps = graph.get_hap_by_pos(res).collect::<Vec<_>>();
            assert_eq!(prev_haps[0], "111");
            assert_eq!(prev_haps[1], "222");

            // Get next for 0
            let res = graph.get_next_pos(0).unwrap();
            assert_eq!(res, 3u32);
            let prev_haps = graph.get_hap_by_pos(res).collect::<Vec<_>>();
            assert_eq!(prev_haps[0], "111");
            assert_eq!(prev_haps[1], "222");

            // Get next for 3. Should be 0.
            assert!(graph.get_next_pos(3).is_none());
            Ok(())
        }

        #[test]
        fn test_get_previous_pos() -> Result<(), std::boxed::Box<dyn std::error::Error>> {
            use vstr::VString;
            // Set up graph.
            let mut reads = ReadFingerprintMap::new();
            reads.insert(ReadAlignmentId::from_name("r1"), VString::from("11"));
            reads.insert(ReadAlignmentId::from_name("r2"), VString::from("22"));
            let mut graph = Graph::try_new(reads.clone(), None)?;
            let mut add_node = |x: VString, y: u32| {
                let _added = graph.fully_add_node(NodeDatum::new(x, y));
            };
            add_node(VString::from("121"), 0);
            add_node(VString::from("111"), 0);
            add_node(VString::from("222"), 3);
            add_node(VString::from("111"), 3);

            // Get previous for 1
            let res = graph.get_previous_pos(1).unwrap();
            assert_eq!(res, 0u32);
            let prev_haps = graph.get_hap_by_pos(res).collect::<Vec<_>>();
            assert_eq!(prev_haps[0], "111");
            assert_eq!(prev_haps[1], "121");

            // Get previous for 3
            let res = graph.get_previous_pos(3).unwrap();
            assert_eq!(res, 0u32);
            let prev_haps = graph.get_hap_by_pos(res).collect::<Vec<_>>();
            assert_eq!(prev_haps[0], "111");
            assert_eq!(prev_haps[1], "121");

            // Get previous for 0
            assert!(graph.get_previous_pos(0).is_none());
            Ok(())
        }

        fn make_graph(reads: &ReadFingerprintMap) -> crate::assembly::variant_graph::Graph {
            use petgraph::stable_graph::NodeIndex;

            const NODES: &[(u8, i32)] = &[
                (b'1', 0), // 0
                (b'1', 1), // 1
                (b'1', 2), // 2
                (b'1', 3), // 3
                (b'2', 0), // 4
                (b'2', 1), // 5
                (b'2', 2), // 6
                (b'2', 3), // 7
            ];

            let mut graph = Graph::try_new(reads.clone(), None).expect("Failed to create Graph");
            for node in NODES
                .iter()
                .map(|(chr, pos)| NodeDatum::from((*chr, *pos as usize)))
            {
                // graph.nodes = ["1-0", "1-1", "1-2", "1-3", "2-0", "2-1", "2-2", "2-3"]
                let (_id, was_new) = graph.fully_add_node(node);
                assert!(was_new);
            }
            let str2idx = |x: &&str| -> u32 {
                let (seq, pos) = x.split_terminator('-').next_tuple().unwrap();
                let seq = seq.as_bytes()[0];
                let pos = pos.parse::<i32>().unwrap();
                NODES
                    .iter()
                    .position(|x| x == &(seq, pos))
                    .expect("Need to find node in set") as u32
            };
            let edge_from = ["1-0", "2-0", "1-1", "2-1", "1-2", "2-2"];
            let edge_to = ["1-1", "2-1", "1-2", "2-2", "1-3", "2-3"];
            for (from, to) in edge_from
                .iter()
                .map(str2idx)
                .zip(edge_to.iter().map(str2idx))
            {
                graph.add_edge(NodeIndex::from(from), NodeIndex::from(to), vec![]);
            }
            graph.pos_edge_map = BTreeMap::new();
            //graph.pos_edge_map = vec![vec![]; 3];
            graph.pos_edge_map.insert(
                0,
                vec![
                    (str2idx(&"1-0"), str2idx(&"1-1"), 2),
                    (str2idx(&"2-0"), str2idx(&"2-1"), 2),
                ],
            );
            graph.pos_edge_map.insert(
                1,
                vec![
                    (str2idx(&"1-1"), str2idx(&"1-2"), 2),
                    (str2idx(&"2-1"), str2idx(&"2-2"), 2),
                ],
            );
            graph.pos_edge_map.insert(
                2,
                vec![
                    (str2idx(&"1-2"), str2idx(&"1-3"), 2),
                    (str2idx(&"2-2"), str2idx(&"2-3"), 2),
                ],
            );
            graph
        }

        #[test]
        fn test_rm_add_edges_ok() -> Result<(), std::boxed::Box<dyn std::error::Error>> {
            use std::collections::BTreeSet;
            use vstr::{VStr, VString};
            let mut logger = env_logger::builder();
            logger
                .format_timestamp_millis()
                .filter_level(log::LevelFilter::Debug)
                .is_test(true);
            let _ = logger.try_init();
            let mut reads = ReadFingerprintMap::new();
            for (read_id, read) in ["x11x", "11xx", "x11x", "x22x", "xx22"].iter().enumerate() {
                reads.insert(
                    ReadAlignmentId::from_name(format!("r{}", read_id + 1)),
                    VString::from(*read),
                );
            }

            let mut graph = make_graph(&reads);
            let paths = AssembledPaths::from_seqs(["11", "22"]);

            graph.rm_add_edges(1, 2, paths.iter())?;
            let nodes = graph
                .node_iter()
                .map(|x| (x.hap.vstr(), x.pos))
                .collect::<BTreeSet<_>>();
            let expected_nodes = [("1", 0), ("1", 3), ("2", 0), ("2", 3), ("11", 1), ("22", 1)]
                .into_iter()
                .map(|(x, y)| (VStr::from(x), y))
                .collect::<BTreeSet<_>>();
            assert_eq!(expected_nodes, nodes);

            let format_edge = |x: &(u32, u32, u32)| -> Option<(String, String)> {
                let edge_index = graph.find_edge(x.0.into(), x.1.into());
                edge_index.and_then(|edge_index| graph.paraphase_format_edge(edge_index, None))
            };
            let edges = graph
                .pos_edge_map
                .iter()
                .flat_map(|(num, iter)| iter.clone().into_iter().map(move |x| (num, x)))
                .filter_map(|(num, edge)| format_edge(&edge).map(|x| (num, x)))
                .collect::<BTreeSet<_>>();
            let edges = edges.into_iter().map(|x| x.1).collect::<BTreeSet<_>>();
            let expected = [
                ("1-0", "11-1"),
                ("11-1", "1-3"),
                ("2-0", "22-1"),
                ("22-1", "2-3"),
            ]
            .into_iter()
            .map(|(x, y)| (x.to_owned(), y.to_owned()))
            .collect::<BTreeSet<_>>();
            assert_eq!(edges, expected);
            let get_data = |idx1: usize, idx2: usize| -> ((String, u32), (String, u32)) {
                let hap_pos = |x: &NodeDatum| -> (String, u32) { (x.hap.to_string(), x.pos) };
                let (from, to, _weight) = graph.pos_edge_map[&idx1][idx2];
                (
                    hap_pos(graph.node_weight(from.into()).expect("No from")),
                    hap_pos(graph.node_weight(to.into()).expect("No to")),
                )
            };
            let test = |x: usize, y: usize, s1: &str, s2: &str, z: u32, w: u32| {
                assert_eq!(
                    get_data(x, y),
                    ((String::from(s1), z), (String::from(s2), w))
                );
            };
            test(0, 0, "1", "11", 0, 1);
            test(0, 1, "2", "22", 0, 1);
            test(1, 0, "11", "1", 1, 3);
            test(1, 1, "22", "2", 1, 3);

            // Now test on edge
            let mut graph = make_graph(&reads);
            graph.rm_add_edges(0, 1, paths.iter())?;

            let nodes = graph
                .node_iter()
                .map(|x| (x.hap.vstr(), x.pos))
                .collect::<BTreeSet<_>>();
            let expected_nodes = [("1", 2), ("1", 3), ("11", 0), ("2", 2), ("2", 3), ("22", 0)]
                .into_iter()
                .map(|(x, y)| (VStr::from(x), y))
                .collect::<BTreeSet<_>>();
            assert_eq!(expected_nodes, nodes);
            let get_data = |idx1: usize, idx2: usize| -> ((String, u32), (String, u32)) {
                let hap_pos = |x: &NodeDatum| -> (String, u32) { (x.hap.to_string(), x.pos) };
                let (from, to, _weight) = graph.pos_edge_map[&idx1][idx2];
                (
                    hap_pos(graph.node_weight(from.into()).expect("No from")),
                    hap_pos(graph.node_weight(to.into()).expect("No to")),
                )
            };
            let test = |x: usize, y: usize, s1: &str, s2: &str, z: u32, w: u32| {
                assert_eq!(
                    get_data(x, y),
                    ((String::from(s1), z), (String::from(s2), w))
                );
            };
            let format_edge = |x: &(u32, u32, u32)| -> Option<(String, String)> {
                let edge_index = graph.find_edge(x.0.into(), x.1.into());
                edge_index.and_then(|edge_index| graph.paraphase_format_edge(edge_index, None))
            };

            let edges = graph
                .pos_edge_map
                .iter()
                .flat_map(|(num, iter)| iter.clone().into_iter().map(move |x| (num, x)))
                .filter_map(|(num, edge)| format_edge(&edge).map(|x| (num, x)))
                .collect::<BTreeSet<_>>();

            let expected = [
                ("1-2", "1-3"),
                ("11-0", "1-2"),
                ("2-2", "2-3"),
                ("22-0", "2-2"),
            ]
            .into_iter()
            .map(|(x, y)| (x.to_owned(), y.to_owned()))
            .collect::<BTreeSet<_>>();
            assert_eq!(
                edges.into_iter().map(|x| x.1).collect::<BTreeSet<_>>(),
                expected
            );

            test(0, 0, "11", "1", 0, 2);
            test(0, 1, "22", "2", 0, 2);
            test(2, 0, "1", "1", 2, 3);
            test(2, 1, "2", "2", 2, 3);
            assert!(!graph.pos_edge_map.contains_key(&1));

            Ok(())
        }

        #[test]
        fn get_segments_ok() -> Result<(), std::boxed::Box<dyn std::error::Error>> {
            use crate::assembly::variant_graph::Graph;
            use crate::assembly::variant_graph::SegmentationClass::*;
            use crate::io::json::{ReadAlignmentId, ReadFingerprintMap};
            use crate::toolkit::range::Range;
            use vstr::VString;
            let mut reads = ReadFingerprintMap::new();
            reads.insert(ReadAlignmentId::from_name("r1"), VString::from("11"));
            reads.insert(ReadAlignmentId::from_name("r2"), VString::from("22"));
            let mut graph = Graph::try_new(reads.clone(), None)?;
            graph.dnhap.insert(0, Two);
            graph.dnhap.insert(1, Ten);
            graph.dnhap.insert(2, Ten);
            graph.dnhap.insert(3, Ten);
            let segments = graph.segment_graph()?;
            assert_eq!(
                *segments
                    .get(&Range::<u32>::new(0, 0))
                    .expect("Range must be present"),
                Two
            );
            assert_eq!(
                *segments
                    .get(&Range::<u32>::new(1, 3))
                    .expect("Range must be present"),
                Ten
            );

            let mut graph = Graph::try_new(reads.clone(), None)?;
            graph.dnhap.insert(0, Two);
            graph.dnhap.insert(1, Two);
            graph.dnhap.insert(2, Ten);
            graph.dnhap.insert(3, Ten);
            let segments = graph.segment_graph()?;
            assert_eq!(
                *segments
                    .get(&Range::<u32>::new(0, 1))
                    .expect("Range must be present"),
                Two
            );
            assert_eq!(
                *segments
                    .get(&Range::<u32>::new(2, 3))
                    .expect("Range must be present"),
                Ten
            );

            let mut graph = Graph::try_new(reads, None)?;
            graph.dnhap.insert(0, Ten);
            graph.dnhap.insert(1, Two);
            graph.dnhap.insert(2, Two);
            graph.dnhap.insert(3, Ten);
            let segments = graph.segment_graph()?;
            log::trace!("segments: {segments:?}");
            let ranges = segments.keys().cloned().collect::<Vec<_>>();
            let expected_ranges = vec![
                Range::<u32>::new(0, 0),
                Range::<u32>::new(1, 2),
                Range::<u32>::new(3, 3),
            ];
            assert_eq!(ranges, expected_ranges);
            for (ivl, val) in &segments {
                match ivl.start {
                    0 => {
                        assert_eq!(ivl.end, 0);
                        assert_eq!(val, &Ten);
                    }
                    1 => {
                        assert_eq!(ivl.end, 2);
                        assert_eq!(val, &Two);
                    }
                    3 => {
                        assert_eq!(ivl.end, 3);
                        assert_eq!(val, &Ten);
                    }
                    _ => {
                        panic!("Not expected");
                    }
                };
            }
            Ok(())
        }

        #[test]
        fn path_ok() -> Result<(), std::boxed::Box<dyn std::error::Error>> {
            use vstr::VString;
            let mut reads = ReadFingerprintMap::new();
            reads.insert(ReadAlignmentId::from_name("r1"), VString::from("11"));
            reads.insert(ReadAlignmentId::from_name("r2"), VString::from("22"));
            let mut graph = Graph::try_new(reads.clone(), None)?;
            graph.init()?;
            let paths = graph.path(Range::<u32>::new(0, 1))?;
            assert_eq!(paths.len(), 2, "paths: {paths:?}");
            assert_eq!(
                paths
                    .iter()
                    .map(std::string::ToString::to_string)
                    .sorted()
                    .collect::<Vec<_>>(),
                vec![String::from("11"), String::from("22")]
            );
            Ok(())
        }

        #[test]
        fn match_reads_and_haps_ok() -> Result<(), std::boxed::Box<dyn std::error::Error>> {
            use vstr::VString;
            let haps = ["21xx", "xx12"]
                .into_iter()
                .map(VString::from)
                .collect::<Vec<_>>();
            let haplotype_per_read = [("r1", "x11x"), ("r2", "x11x")]
                .into_iter()
                .map(|(x, y)| (ReadAlignmentId::from_name(x), VString::from(y)))
                .collect::<ReadFingerprintMap>();
            let res = Graph::match_reads_and_haps(
                &haplotype_per_read,
                &haps[..],
                /* min_match= */ None,
            )?;
            let unique = &res.support_reads;
            log::trace!("unique: {unique:?}");
            let match0 = unique.get(&0).unwrap();
            let match1 = unique.get(&1).unwrap();
            assert_eq!(
                match0
                    .iter()
                    .map(|x| x.path.to_string())
                    .collect::<Vec<_>>(),
                &["x11x", "x11x"]
            );
            assert_eq!(
                match1
                    .iter()
                    .map(|x| x.path.to_string())
                    .collect::<Vec<_>>(),
                &["x11x", "x11x"]
            );
            Ok(())
        }

        #[test]
        fn test_get_matching_hap_ok() -> Result<(), std::boxed::Box<dyn std::error::Error>> {
            use crate::assembly::variant_graph::Graph;
            use std::collections::BTreeMap;
            use vstr::VStr;

            let nodes = [(0, ["11", "22"]), (2, ["11", "22"])]
                .into_iter()
                .map(|(key, vec)| (key, (vec.into_iter().map(VStr::from).collect::<Vec<_>>())))
                .collect::<BTreeMap<_, _>>();
            let (hap, matches) = Graph::get_matching_hap(&nodes, 0, VStr::from("x11x"))?;
            assert_eq!(hap, "x1");
            let (score, hits) = matches.expect("No matches");
            assert_eq!(score, 1);
            assert_eq!(hits, vec![VStr::from("11")]);

            let (hap, matches) = Graph::get_matching_hap(&nodes, 2, VStr::from("x11x"))?;
            assert_eq!(hap, "1x");
            let (score, hits) = matches.expect("No matches");
            assert_eq!(score, 1);
            assert_eq!(hits, vec![VStr::from("11")]);
            Ok(())
        }

        #[test]
        fn test_merge_two_pos_ok() -> Result<(), std::boxed::Box<dyn std::error::Error>> {
            use crate::assembly::variant_graph::Graph;
            use crate::io::json::{ReadAlignmentId, ReadFingerprintMap};
            use vstr::{VStr, VString};

            let mut logger = env_logger::builder();
            logger
                .format_timestamp_millis()
                .filter_level(log::LevelFilter::Debug)
                .is_test(true);
            let _ = logger.try_init();

            let data = ["x11x", "11xx", "x11x", "x22x", "xx22"]
                .iter()
                .enumerate()
                .map(|(idx, hap)| {
                    (
                        ReadAlignmentId::from_name(format!("r{}", idx + 1)),
                        VString::from(*hap),
                    )
                })
                .collect::<ReadFingerprintMap>();
            let graph = Graph::try_new(data, None)?;
            let nodes = [(0, ["11", "22"]), (2, ["11", "22"])]
                .into_iter()
                .map(|(key, v)| {
                    (
                        key as u32,
                        v.into_iter()
                            .map(VStr::from)
                            .collect::<std::collections::BTreeSet<_>>(),
                    )
                })
                .collect::<std::collections::BTreeMap<_, _>>();
            let (sub_hap, dnext, dbefore) = graph.merge_two_pos(&nodes)?;
            assert_eq!(
                dnext[&VStr::from("11")].iter().next(),
                Some(&VStr::from("11"))
            );
            assert_eq!(
                dnext[&VStr::from("22")].iter().next(),
                Some(&VStr::from("22"))
            );
            assert_eq!(
                dbefore[&VStr::from("11")].iter().next(),
                Some(&VStr::from("11"))
            );
            assert_eq!(
                dbefore[&VStr::from("22")].iter().next(),
                Some(&VStr::from("22"))
            );
            assert_eq!(
                sub_hap[&VString::from("1111")].clone(),
                vec![
                    &ReadAlignmentId::from_name("r1"),
                    &ReadAlignmentId::from_name("r3")
                ]
            );
            assert_eq!(
                sub_hap[&VString::from("2222")].clone(),
                vec![&ReadAlignmentId::from_name("r4")]
            );
            assert_eq!(sub_hap.len(), 2);
            Ok(())
        }

        #[test]
        fn rescue_missing_ok() {
            use crate::assembly::variant_graph::Graph;
            use std::collections::*;
            use vstr::VString;
            let left_seq = VString::from("11");
            let right_seq = VString::from("22");
            let left = vec![&left_seq];
            let right = vec![&right_seq];
            let dnext: BTreeMap<VString, BTreeSet<VString>> = [("11", "22")]
                .into_iter()
                .map(|(x, y)| {
                    (
                        VString::from(x),
                        [y].into_iter().map(VString::from).collect::<BTreeSet<_>>(),
                    )
                })
                .collect::<_>();
            let dbefore: BTreeMap<VString, BTreeSet<VString>> = [("22", "11")]
                .into_iter()
                .map(|(x, y)| {
                    (
                        VString::from(x),
                        [y].into_iter().map(VString::from).collect::<BTreeSet<_>>(),
                    )
                })
                .collect::<_>();

            let rescued = Graph::rescue_missing(&left, &right, &dnext, &dbefore);
            assert_eq!(
                rescued,
                [VString::from("1122")].into_iter().collect::<BTreeSet<_>>()
            );
        }

        #[test]
        fn get_missing_ok() {
            use vstr::VString;
            // Set up graph.
            let haps_left = ["11", "22"]
                .into_iter()
                .map(VString::from)
                .collect::<Vec<_>>();
            let haps_right = ["12", "21"]
                .into_iter()
                .map(VString::from)
                .collect::<Vec<_>>();
            let test_haps = [VString::from("1112")]
                .into_iter()
                .collect::<std::collections::BTreeSet<_>>();
            let (left, right) = Graph::get_missing(&test_haps, &haps_left[..], &haps_right);
            assert_eq!(left, vec![&VString::from("22")]);
            assert_eq!(right, vec![&VString::from("21")]);
        }

        #[test]
        fn get_highest_cn_ok() -> Result<(), DError> {
            use crate::assembly::variant_graph::Graph;
            use crate::io::json::ReadAlignmentId;
            use vstr::VString;
            let reads = [("r1", "11111"), ("r2", "22222")]
                .into_iter()
                .map(|(name, fprint)| (ReadAlignmentId::from_name(name), VString::from(fprint)))
                .collect::<std::collections::BTreeMap<_, _>>();
            let graph = Graph::try_new(reads, None)?;
            let (highest_cn, _) = graph.get_highest_cn(["11111", "22222"].into_iter())?;
            assert_eq!(highest_cn, 2);
            let (highest_cn, _) =
                graph.get_highest_cn(["121xxx", "111111", "xxx111"].into_iter())?;
            assert_eq!(highest_cn, 2);
            let (highest_cn, _) =
                graph.get_highest_cn(["1211xx", "111111", "xxx111"].into_iter())?;
            assert_eq!(highest_cn, 3);
            Ok(())
        }

        #[test]
        fn order_blocks_by_size_ok() -> Result<(), DError> {
            use crate::assembly::node_datum::NodeDatum;
            use crate::assembly::variant_graph::Graph;
            use crate::io::json::ReadAlignmentId;
            use vstr::VString;
            let reads = ["111x", "211x", "x111", "x112", "xx12", "1111"]
                .into_iter()
                .enumerate()
                .map(|(idx, item)| {
                    (
                        ReadAlignmentId::from_name(format!("r{}", idx + 1)),
                        VString::from(item),
                    )
                })
                .collect::<std::collections::BTreeMap<_, _>>();
            let mut graph = Graph::try_new(reads, None)?;
            for node in ["11-0", "22-0", "11-2", "22-2", "111-4", "222-4"]
                .into_iter()
                .map(|x| NodeDatum::try_from(x).unwrap())
            {
                let _added = graph.fully_add_node(node);
            }
            let block_order = graph.order_blocks_by_size();
            assert_eq!(block_order, &[[2, 4, 2, 3u32], [0, 2, 2, 2u32]]);
            Ok(())
        }

        #[test]
        fn extend_pivot_blocks_ok() -> Result<(), DError> {
            use crate::assembly::node_datum::NodeDatum;
            use crate::assembly::variant_graph::Graph;
            use crate::assembly::variant_graph::SegmentationClass::*;
            use crate::io::json::ReadAlignmentId;
            let reads = [
                "x2111x", "x11xxx", "xxx22x", "x2111x", "xxx122", "1211xx", "xx1122", "xx11xx",
                "x111x1", "x1x12x",
            ]
            .into_iter()
            .enumerate()
            .map(|(idx, hap)| {
                (
                    ReadAlignmentId::from_name(format!("r{}", (idx % 10))),
                    vstr::VString::from(hap),
                )
            })
            .collect::<std::collections::BTreeMap<_, _>>();
            let mut graph = Graph::try_new(reads, None)?;
            for node in ["121-0", "111-0", "122-3", "111-3"]
                .into_iter()
                .map(|x| NodeDatum::try_from(x).unwrap())
            {
                let _added = graph.fully_add_node(node);
            }
            graph.add_edge(0.into(), 0.into(), vec![]);
            graph.dnhap.insert(2, Ten);
            //graph.pos_edge_map = vec![vec![], vec![], vec![(0, 0, 2), (0, 0, 3)], vec![]];
            graph.pos_edge_map = BTreeMap::new();
            graph.pos_edge_map.insert(0, vec![]);
            graph.pos_edge_map.insert(1, vec![]);
            graph.pos_edge_map.insert(2, vec![(0, 0, 2), (0, 0, 3)]);
            graph.pos_edge_map.insert(3, vec![]);
            graph.edge_info = vec![vec![], vec![], vec![2, 3], vec![]];
            let extended_haps = graph.extend_pivot_blocks(["111xxx"]);
            assert_eq!(extended_haps.len(), 1);
            assert_eq!(
                extended_haps
                    .iter()
                    .next()
                    .map(std::string::ToString::to_string)
                    .unwrap(),
                "1111xx"
            );
            Ok(())
        }

        #[test]
        fn filter_low_support_haps_ok() -> DResult {
            let reads = [
                "11x", "22x", "x12", "x22", "x2x", "x22", "x11", "xx1", "xx1",
            ]
            .into_iter()
            .enumerate()
            .map(|(idx, hap)| {
                (
                    ReadAlignmentId::from_name(format!("r{}", idx + 1)),
                    vstr::VString::from(hap),
                )
            })
            .collect::<std::collections::BTreeMap<_, _>>();
            let mut graph = Graph::try_new(reads, None)?;
            graph.settings.min_hap_support = 3;
            let filtered_haps = graph.filter_low_support_haps(&AssembledPaths::from_seqs(
                ["112", "111", "222"].into_iter(),
            ))?;
            assert_eq!(
                filtered_haps.iter().map(|x| x.vstr()).collect::<Vec<_>>(),
                vec![vstr::VStr::from("111"), vstr::VStr::from("222")]
            );
            graph.settings.min_hap_support = 1;
            let filtered_haps = graph.filter_low_support_haps(&AssembledPaths::from_seqs(
                ["112", "111", "222"].into_iter(),
            ))?;
            assert_eq!(
                filtered_haps.iter().map(|x| x.vstr()).collect::<Vec<_>>(),
                vec![
                    vstr::VStr::from("111"),
                    vstr::VStr::from("112"),
                    vstr::VStr::from("222")
                ]
            );
            Ok(())
        }

        #[test]
        fn run_ok() -> DResult {
            use vstr::VString;
            let reads = ["11", "22", "11", "22", "11", "22"]
                .into_iter()
                .enumerate()
                .map(|(idx, hap)| {
                    (
                        ReadAlignmentId::from_name(format!("r{}", idx + 1)),
                        VString::from(hap),
                    )
                })
                .collect::<std::collections::BTreeMap<_, _>>();
            let settings = variant_graph::Settings::from_pivot(Some(1));
            let mut graph = Graph::try_new(reads, Some(settings))?;
            graph.init()?;
            let res = graph.assemble_haps()?;
            assert_eq!(
                res.into_inner()
                    .into_iter()
                    .map(|x| x.to_string())
                    .sorted()
                    .collect::<Vec<_>>(),
                ["11", "22"]
                    .into_iter()
                    .map(String::from)
                    .collect::<Vec<_>>()
            );
            Ok(())
        }

        #[test]
        fn filter_low_complex_ok() -> DResult {
            use itertools::Itertools;
            let haps = [
                "121xxxxxxxxxx",
                "212xxxxxxxxxx",
                "xxx1xxxxxxxxx",
                "xxx2122222222",
                "xxxx222222222",
                "xxxxx11111111",
            ]
            .into_iter()
            .map(vstr::VStr::from)
            .sorted()
            .collect::<Vec<_>>();
            let reads = [
                ("m54086U_220112_213432/103743586/ccs", "xxx1xxxxxxxxx"),
                ("m54086U_220112_213432/108529606/ccs", "xxxx1222222xx"),
                ("m54086U_220112_213432/110036868/ccs", "xxx21xxxxxxxx"),
                ("m54086U_220112_213432/11665889/ccs", "x12xxxxxxxxxx"),
                ("m54086U_220112_213432/119212720/ccs", "xxx21xxxxxxxx"),
                ("m54086U_220112_213432/123667055/ccs", "xxxxxx2222x22"),
                ("m54086U_220112_213432/129172024/ccs", "xxx12xxxxxxxx"),
                ("m54086U_220112_213432/132579760/ccs", "xxxxx22222222"),
                ("m54086U_220112_213432/133891184/ccs", "xxxxxxx222222"),
                ("m54086U_220112_213432/135923990/ccs", "xxxxx11111111"),
                ("m54086U_220112_213432/136381648/ccs", "x21xxxxxxxxxx"),
                ("m54086U_220112_213432/137366144/ccs", "xxx2xxxxxxxxx"),
                ("m54086U_220112_213432/146474465/ccs", "xxxx2xxxxxxxx"),
                ("m54086U_220112_213432/147720103/ccs", "212xxxxxxxxxx"),
                ("m54086U_220112_213432/150339693/ccs", "x21xxxxxxxxxx"),
                ("m54086U_220112_213432/156894020/ccs", "xxxxxx1111111"),
                ("m54086U_220112_213432/157878867/ccs", "121xxxxxxxxxx"),
                ("m54086U_220112_213432/159712931/ccs", "xxx2xxxxxxxxx"),
                ("m54086U_220112_213432/165676282/ccs", "121xxxxxxxxxx"),
                ("m54086U_220112_213432/16909085/ccs", "xxx1xxxxxxxxx"),
                ("m54086U_220112_213432/171443538/ccs", "xxx1xxxxxxxxx"),
                ("m54086U_220112_213432/178193776/ccs", "xxxxx22222222"),
                ("m54086U_220112_213432/179963762/ccs", "121xxxxxxxxxx"),
                ("m54086U_220112_213432/26346554/ccs", "xxx2xxxxxxxxx"),
                ("m54086U_220112_213432/29624360/ccs", "xxx1xxxxxxxxx"),
                ("m54086U_220112_213432/30540767/ccs", "xxxx122222222"),
                ("m54086U_220112_213432/43581827/ccs", "xxxx1xxxxxxxx"),
                ("m54086U_220112_213432/525604/ccs", "xxxxx11111111"),
                ("m54086U_220112_213432/56231844/ccs", "212xxxxxxxxxx"),
                ("m54086U_220112_213432/57672451/ccs", "121xxxxxxxxxx"),
                ("m54086U_220112_213432/60623188/ccs", "212xxxxxxxxxx"),
                ("m54086U_220112_213432/61015098/ccs", "xxxxxx1111111"),
                ("m54086U_220112_213432/62915752/ccs", "xxxxxxxxx1111"),
                ("m54086U_220112_213432/66456232/ccs", "212xxxxxxxxxx"),
                ("m54086U_220112_213432/67699442/ccs", "xxxx22xxxxxxx"),
                ("m54086U_220112_213432/71567283/ccs", "1xxxxxxxxxxxx"),
                ("m54086U_220112_213432/73205791/ccs", "2xxxxxxxxxxxx"),
                ("m54086U_220112_213432/74252490/ccs", "xxx1xxxxxxxxx"),
                ("m54086U_220112_213432/78777158/ccs", "xxxxx222xx2x2"),
                ("m54086U_220112_213432/84085293/ccs", "21xxxxxxxxxxx"),
                ("m54086U_220112_213432/86442681/ccs", "xxx1xxxxxxxxx"),
                ("m54086U_220112_213432/91161760/ccs", "xxxxx11111111"),
                ("m54086U_220112_213432/93062608/ccs", "x21xxxxxxxxxx"),
                ("m54086U_220112_213432/93128452/ccs", "121xxxxxxxxxx"),
                ("m54086U_220112_213432/9962031/ccs", "xxx1xxxxxxxxx"),
            ]
            .into_iter()
            .map(|(k, v)| (ReadAlignmentId::from_name(k), vstr::VString::from(v)))
            .collect::<ReadFingerprintMap>();
            let res = Graph::filter_low_support_haps_detail(
                &AssembledPaths::from_seqs(haps.iter()),
                4,
                &reads,
            )?;
            let expected = AssembledPaths::from_seqs([
                "212xxxxxxxxxx",
                "121xxxxxxxxxx",
                "xxx2122222222",
                "xxx1xxxxxxxxx",
                "xxxxx11111111",
            ]);
            assert_eq!(expected, res);
            Ok(())
        }
    }
}
